services:
  rampart:
    image: ghcr.io/therebelrobot/rampart:latest
    container_name: rampart
    restart: unless-stopped
    ports:
      - "8080:8080"
    read_only: true
    security_opt:
      - no-new-privileges:true
